theme = "slidenote"
baseurl = "http://alexzirbel.com/"
languageCode = "en-us"
title = "Alex Zirbel"
author = "azirbel"

[params]
  logo      = "/images/logo.jpg"
  copyright = "Alex Zirbel. All rights reserved."
  twitter   = "https://twitter.com/alexzirbel"
  facebook  = "https://www.facebook.com/alex.zirbel"
  github    = "https://github.com/azirbel/"
  email     = "alexzirbel@gmail.com"
  analytics = "UA-12345678-9"
